// <auto-generated />
using System;
using ControlePedidosAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlePedidosAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ControlePedidosAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tradicional"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Especial"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Doce"
                        });
                });

            modelBuilder.Entity("ControlePedidosAPI.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PizzaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PizzaId");

                    b.ToTable("ItensPedido");
                });

            modelBuilder.Entity("ControlePedidosAPI.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("ControlePedidosAPI.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Molho de tomate, mussarela e manjericão",
                            Disponivel = true,
                            Nome = "Margherita",
                            Preco = 35.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descricao = "Calabresa fatiada, cebola e azeitona",
                            Disponivel = true,
                            Nome = "Calabresa",
                            Preco = 38.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descricao = "Mussarela, provolone, parmesão e gorgonzola",
                            Disponivel = true,
                            Nome = "Quatro Queijos",
                            Preco = 45.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            Descricao = "Frango desfiado com catupiry cremoso",
                            Disponivel = true,
                            Nome = "Frango com Catupiry",
                            Preco = 42.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descricao = "Chocolate ao leite com morangos frescos",
                            Disponivel = true,
                            Nome = "Chocolate com Morango",
                            Preco = 40.00m
                        });
                });

            modelBuilder.Entity("ControlePedidosAPI.Models.ItemPedido", b =>
                {
                    b.HasOne("ControlePedidosAPI.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlePedidosAPI.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("ControlePedidosAPI.Models.Pizza", b =>
                {
                    b.HasOne("ControlePedidosAPI.Models.Categoria", "Categoria")
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ControlePedidosAPI.Models.Categoria", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("ControlePedidosAPI.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
